// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: guests.sql

package dbgen

import (
	"context"
	"time"
)

const createRoomGuest = `-- name: CreateRoomGuest :one
INSERT INTO room_guests (id, room_id, display_name, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, room_id, display_name, token_hash, expires_at
`

type CreateRoomGuestParams struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"room_id"`
	DisplayName string    `json:"display_name"`
	TokenHash   string    `json:"token_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateRoomGuest(ctx context.Context, arg CreateRoomGuestParams) (RoomGuest, error) {
	row := q.db.QueryRowContext(ctx, createRoomGuest,
		arg.ID,
		arg.RoomID,
		arg.DisplayName,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RoomGuest
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const getRoomGuest = `-- name: GetRoomGuest :one
SELECT g.id, g.room_id, g.display_name, g.token_hash, g.expires_at FROM room_guests g
JOIN rooms r ON r.id = g.room_id
WHERE g.token_hash = $1 AND r.invite_code = $2 AND g.expires_at > $3 AND r.kind = 'group'
`

type GetRoomGuestParams struct {
	TokenHash  string    `json:"token_hash"`
	InviteCode string    `json:"invite_code"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) GetRoomGuest(ctx context.Context, arg GetRoomGuestParams) (RoomGuest, error) {
	row := q.db.QueryRowContext(ctx, getRoomGuest, arg.TokenHash, arg.InviteCode, arg.ExpiresAt)
	var i RoomGuest
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.DisplayName,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeRoomGuest = `-- name: RevokeRoomGuest :exec
UPDATE room_guests SET expires_at = $3
WHERE token_hash = $1 AND room_id = $2
`

type RevokeRoomGuestParams struct {
	TokenHash string    `json:"token_hash"`
	RoomID    string    `json:"room_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) RevokeRoomGuest(ctx context.Context, arg RevokeRoomGuestParams) error {
	_, err := q.db.ExecContext(ctx, revokeRoomGuest, arg.TokenHash, arg.RoomID, arg.ExpiresAt)
	return err
}
