// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package dbgen

import (
	"context"
	"time"
)

const createRoomMessage = `-- name: CreateRoomMessage :one
INSERT INTO room_messages (id, room_id, user_id, body, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, room_id, user_id, body, created_at
`

type CreateRoomMessageParams struct {
	ID        string    `json:"id"`
	RoomID    string    `json:"room_id"`
	UserID    string    `json:"user_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateRoomMessage(ctx context.Context, arg CreateRoomMessageParams) (RoomMessage, error) {
	row := q.db.QueryRowContext(ctx, createRoomMessage,
		arg.ID,
		arg.RoomID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
	)
	var i RoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listRoomMessages = `-- name: ListRoomMessages :many
SELECT
    m.id,
    m.room_id,
    m.user_id,
    m.body,
    m.created_at,
    u.username,
    u.display_name
FROM room_messages m
JOIN users u ON u.id = m.user_id
WHERE m.room_id = $1
ORDER BY m.created_at DESC, m.id DESC
LIMIT 100
`

type ListRoomMessagesRow struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"room_id"`
	UserID      string    `json:"user_id"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListRoomMessages(ctx context.Context, roomID string) ([]ListRoomMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomMessagesRow{}
	for rows.Next() {
		var i ListRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
