// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const createRoomMessage = `-- name: CreateRoomMessage :one
INSERT INTO room_messages (id, room_id, user_id, body, created_at, guest_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_id, user_id, body, created_at, guest_id
`

type CreateRoomMessageParams struct {
	ID        string         `json:"id"`
	RoomID    string         `json:"room_id"`
	UserID    sql.NullString `json:"user_id"`
	Body      string         `json:"body"`
	CreatedAt time.Time      `json:"created_at"`
	GuestID   sql.NullString `json:"guest_id"`
}

func (q *Queries) CreateRoomMessage(ctx context.Context, arg CreateRoomMessageParams) (RoomMessage, error) {
	row := q.db.QueryRowContext(ctx, createRoomMessage,
		arg.ID,
		arg.RoomID,
		arg.UserID,
		arg.Body,
		arg.CreatedAt,
		arg.GuestID,
	)
	var i RoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.GuestID,
	)
	return i, err
}

const listRoomMessages = `-- name: ListRoomMessages :many
SELECT id, room_id, author_id, body, created_at, username, display_name FROM (
    SELECT
        m.id,
        m.room_id,
        COALESCE(m.user_id, m.guest_id)::text AS author_id,
        m.body,
        m.created_at,
        COALESCE(u.username, '')::text AS username,
        COALESCE(u.display_name, g.display_name)::text AS display_name
    FROM room_messages m
    LEFT JOIN users u ON u.id = m.user_id
    LEFT JOIN room_guests g ON g.id = m.guest_id
    WHERE m.room_id = $1
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 100
) recent
ORDER BY recent.created_at, recent.id
`

type ListRoomMessagesRow struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"room_id"`
	AuthorID    string    `json:"author_id"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListRoomMessages(ctx context.Context, roomID string) ([]ListRoomMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomMessages, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomMessagesRow{}
	for rows.Next() {
		var i ListRoomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
