// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

type Room struct {
	ID         string `json:"id"`
	InviteCode string `json:"invite_code"`
	Name       string `json:"name"`
	OwnerID    string `json:"owner_id"`
	CreatedAt  int64  `json:"created_at"`
}

type Session struct {
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    int64  `json:"created_at"`
}
