// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type DesktopDiagnostic struct {
	UserID     string          `json:"user_id"`
	EventID    string          `json:"event_id"`
	CallID     string          `json:"call_id"`
	ReceivedAt time.Time       `json:"received_at"`
	Payload    json.RawMessage `json:"payload"`
}

type DesktopLogin struct {
	ID        string         `json:"id"`
	Challenge string         `json:"challenge"`
	UserID    sql.NullString `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
}

type DirectCall struct {
	ID         string       `json:"id"`
	RoomID     string       `json:"room_id"`
	CallerID   string       `json:"caller_id"`
	CalleeID   string       `json:"callee_id"`
	Status     string       `json:"status"`
	CreatedAt  time.Time    `json:"created_at"`
	AnsweredAt sql.NullTime `json:"answered_at"`
	EndedAt    sql.NullTime `json:"ended_at"`
}

type DirectMessage struct {
	ID          string    `json:"id"`
	SenderID    string    `json:"sender_id"`
	RecipientID string    `json:"recipient_id"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
}

type FriendRequest struct {
	ID         string    `json:"id"`
	SenderID   string    `json:"sender_id"`
	ReceiverID string    `json:"receiver_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Friendship struct {
	UserID    string    `json:"user_id"`
	FriendID  string    `json:"friend_id"`
	CreatedAt time.Time `json:"created_at"`
}

type OpenCallParticipant struct {
	UserID    string    `json:"user_id"`
	CallID    string    `json:"call_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Passkey struct {
	ID           string          `json:"id"`
	UserID       string          `json:"user_id"`
	CredentialID []byte          `json:"credential_id"`
	Name         string          `json:"name"`
	Credential   json.RawMessage `json:"credential"`
	CreatedAt    time.Time       `json:"created_at"`
	LastUsedAt   sql.NullTime    `json:"last_used_at"`
}

type PasskeyCeremony struct {
	TokenHash   string          `json:"token_hash"`
	UserID      sql.NullString  `json:"user_id"`
	Kind        string          `json:"kind"`
	Name        string          `json:"name"`
	SessionData json.RawMessage `json:"session_data"`
	ExpiresAt   time.Time       `json:"expires_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

type PasskeyUser struct {
	UserID    string    `json:"user_id"`
	Handle    []byte    `json:"handle"`
	CreatedAt time.Time `json:"created_at"`
}

type Room struct {
	ID             string         `json:"id"`
	InviteCode     string         `json:"invite_code"`
	Name           string         `json:"name"`
	OwnerID        string         `json:"owner_id"`
	Kind           string         `json:"kind"`
	CreatedAt      time.Time      `json:"created_at"`
	LivekitRoomSid sql.NullString `json:"livekit_room_sid"`
}

type RoomGuest struct {
	ID          string    `json:"id"`
	RoomID      string    `json:"room_id"`
	DisplayName string    `json:"display_name"`
	TokenHash   string    `json:"token_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

type RoomMember struct {
	RoomID    string    `json:"room_id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RoomMessage struct {
	ID        string         `json:"id"`
	RoomID    string         `json:"room_id"`
	UserID    sql.NullString `json:"user_id"`
	Body      string         `json:"body"`
	CreatedAt time.Time      `json:"created_at"`
	GuestID   sql.NullString `json:"guest_id"`
}

type Session struct {
	TokenHash  string    `json:"token_hash"`
	UserID     string    `json:"user_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

type User struct {
	ID                 string    `json:"id"`
	Username           string    `json:"username"`
	Email              string    `json:"email"`
	DisplayName        string    `json:"display_name"`
	PasswordHash       string    `json:"password_hash"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	MustChangePassword bool      `json:"must_change_password"`
}

type UserSetting struct {
	UserID       string    `json:"user_id"`
	VideoQuality string    `json:"video_quality"`
	UpdatedAt    time.Time `json:"updated_at"`
}
