// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: passkeys.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const consumePasskeyCeremony = `-- name: ConsumePasskeyCeremony :one
DELETE FROM passkey_ceremonies
WHERE token_hash = $1 AND kind = $2 AND expires_at > $3
RETURNING token_hash, user_id, kind, name, session_data, expires_at, created_at
`

type ConsumePasskeyCeremonyParams struct {
	TokenHash string    `json:"token_hash"`
	Kind      string    `json:"kind"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) ConsumePasskeyCeremony(ctx context.Context, arg ConsumePasskeyCeremonyParams) (PasskeyCeremony, error) {
	row := q.db.QueryRowContext(ctx, consumePasskeyCeremony, arg.TokenHash, arg.Kind, arg.ExpiresAt)
	var i PasskeyCeremony
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Kind,
		&i.Name,
		&i.SessionData,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPasskeys = `-- name: CountPasskeys :one
SELECT count(*) FROM passkeys WHERE user_id = $1
`

func (q *Queries) CountPasskeys(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPasskeys, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkeys (id, user_id, credential_id, name, credential, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, credential_id, name, credential, created_at, last_used_at
`

type CreatePasskeyParams struct {
	ID           string          `json:"id"`
	UserID       string          `json:"user_id"`
	CredentialID []byte          `json:"credential_id"`
	Name         string          `json:"name"`
	Credential   json.RawMessage `json:"credential"`
	CreatedAt    time.Time       `json:"created_at"`
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (Passkey, error) {
	row := q.db.QueryRowContext(ctx, createPasskey,
		arg.ID,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.Credential,
		arg.CreatedAt,
	)
	var i Passkey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Name,
		&i.Credential,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createPasskeyCeremony = `-- name: CreatePasskeyCeremony :exec
INSERT INTO passkey_ceremonies (token_hash, user_id, kind, name, session_data, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePasskeyCeremonyParams struct {
	TokenHash   string          `json:"token_hash"`
	UserID      sql.NullString  `json:"user_id"`
	Kind        string          `json:"kind"`
	Name        string          `json:"name"`
	SessionData json.RawMessage `json:"session_data"`
	ExpiresAt   time.Time       `json:"expires_at"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) CreatePasskeyCeremony(ctx context.Context, arg CreatePasskeyCeremonyParams) error {
	_, err := q.db.ExecContext(ctx, createPasskeyCeremony,
		arg.TokenHash,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.SessionData,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPasskeyCeremonies = `-- name: DeleteExpiredPasskeyCeremonies :exec
DELETE FROM passkey_ceremonies WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredPasskeyCeremonies(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasskeyCeremonies, expiresAt)
	return err
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM passkeys WHERE id = $1 AND user_id = $2
`

type DeletePasskeyParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePasskey(ctx context.Context, arg DeletePasskeyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePasskey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensurePasskeyUser = `-- name: EnsurePasskeyUser :one
INSERT INTO passkey_users (user_id, handle, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, handle, created_at
`

type EnsurePasskeyUserParams struct {
	UserID    string    `json:"user_id"`
	Handle    []byte    `json:"handle"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) EnsurePasskeyUser(ctx context.Context, arg EnsurePasskeyUserParams) (PasskeyUser, error) {
	row := q.db.QueryRowContext(ctx, ensurePasskeyUser, arg.UserID, arg.Handle, arg.CreatedAt)
	var i PasskeyUser
	err := row.Scan(&i.UserID, &i.Handle, &i.CreatedAt)
	return i, err
}

const getPasskeyUser = `-- name: GetPasskeyUser :one
SELECT user_id, handle, created_at FROM passkey_users WHERE user_id = $1
`

func (q *Queries) GetPasskeyUser(ctx context.Context, userID string) (PasskeyUser, error) {
	row := q.db.QueryRowContext(ctx, getPasskeyUser, userID)
	var i PasskeyUser
	err := row.Scan(&i.UserID, &i.Handle, &i.CreatedAt)
	return i, err
}

const getUserByPasskey = `-- name: GetUserByPasskey :one
SELECT u.id, u.username, u.email, u.display_name, u.password_hash, u.created_at, u.updated_at, u.must_change_password
FROM passkeys p
JOIN passkey_users pu ON pu.user_id = p.user_id
JOIN users u ON u.id = p.user_id
WHERE p.credential_id = $1 AND pu.handle = $2
LIMIT 1
`

type GetUserByPasskeyParams struct {
	CredentialID []byte `json:"credential_id"`
	Handle       []byte `json:"handle"`
}

func (q *Queries) GetUserByPasskey(ctx context.Context, arg GetUserByPasskeyParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPasskey, arg.CredentialID, arg.Handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, credential_id, name, credential, created_at, last_used_at FROM passkeys WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPasskeys(ctx context.Context, userID string) ([]Passkey, error) {
	rows, err := q.db.QueryContext(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Passkey{}
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.Credential,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeyCredential = `-- name: UpdatePasskeyCredential :execrows
UPDATE passkeys
SET credential = $2, last_used_at = $3
WHERE credential_id = $1
`

type UpdatePasskeyCredentialParams struct {
	CredentialID []byte          `json:"credential_id"`
	Credential   json.RawMessage `json:"credential"`
	LastUsedAt   sql.NullTime    `json:"last_used_at"`
}

func (q *Queries) UpdatePasskeyCredential(ctx context.Context, arg UpdatePasskeyCredentialParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePasskeyCredential, arg.CredentialID, arg.Credential, arg.LastUsedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
