// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rooms.sql

package dbgen

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, invite_code, name, owner_id, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, invite_code, name, owner_id, created_at
`

type CreateRoomParams struct {
	ID         string `json:"id"`
	InviteCode string `json:"invite_code"`
	Name       string `json:"name"`
	OwnerID    string `json:"owner_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.ID,
		arg.InviteCode,
		arg.Name,
		arg.OwnerID,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByInviteCode = `-- name: GetRoomByInviteCode :one
SELECT id, invite_code, name, owner_id, created_at FROM rooms WHERE invite_code = ? LIMIT 1
`

func (q *Queries) GetRoomByInviteCode(ctx context.Context, inviteCode string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomByInviteCode, inviteCode)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.InviteCode,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
