// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package dbgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $4)
`

type CreateSessionParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.username, u.email, u.display_name, u.password_hash, u.created_at, u.updated_at, u.must_change_password FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > $2
LIMIT 1
`

type GetSessionUserParams struct {
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MustChangePassword,
	)
	return i, err
}

const isUserOnline = `-- name: IsUserOnline :one
SELECT EXISTS (
    SELECT 1
    FROM sessions
    WHERE user_id = $1 AND expires_at > $2 AND last_seen_at >= $3
) AS online
`

type IsUserOnlineParams struct {
	UserID     string    `json:"user_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) IsUserOnline(ctx context.Context, arg IsUserOnlineParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserOnline, arg.UserID, arg.ExpiresAt, arg.LastSeenAt)
	var online bool
	err := row.Scan(&online)
	return online, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = $2
WHERE token_hash = $1
  AND last_seen_at < $2 - INTERVAL '10 seconds'
`

type TouchSessionParams struct {
	TokenHash  string    `json:"token_hash"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.TokenHash, arg.LastSeenAt)
	return err
}
